## Set up Project

In [1]:
using BenchmarkTools
using Wquantiles

## Using Quantile Functions with Differing Types

Wquantile([1 2; 3 4; 5 6; 7 8; 9 10; 11 14; 15 32; 7 4; 9 10; 11 21], [1, 1, 2, 1, 1, 2, 1, 3, 5, 1], [0.25, 0.5, 0.6, 0.75])

In [2]:
wquantile(UInt8[1,3,5,7,9,11,15,7,9,11], [1,1,2,1,1,2,1,3,5,1], [0.25, 0.5, 0.6, 0.75])

4-element Vector{UInt8}:
 0x07
 0x09
 0x0b
 0x0b

In [3]:
wquantile([2,4,6,8,10,14,32,4,10,21], [1,1,2,1,1,2,1,3,5,1], [0.25, 0.5, 0.6, 0.75])

4-element Vector{Int64}:
  6
 10
 14
 14

In [4]:
wquantile(UInt8[1,2,3,4,5,6,7,8,9,10], [1, 1, 2, 1, 1, 2, 1, 3, 5, 1], [0.25, 0.5, 0.6, 0.75])

4-element Vector{UInt8}:
 0x05
 0x08
 0x09
 0x0a

In [5]:
wquantile(UInt8[1,2,3,4,5,6,7,8,9,10], [1, 1, 2, 1, 1, 2, 1, 3, 5, 1], [0.25, 0.5, 0.6, 0.75])

4-element Vector{UInt8}:
 0x05
 0x08
 0x09
 0x0a

## Test Performance of Quantile Functions

In [6]:
@btime wquantile([1,2,3,4,5,6,7,8,9,10], [1, 1, 2, 1, 1, 2, 1, 1, 5, 1], [0.25, 0.5, 0.6, 0.75])

  409.690 ns (14 allocations: 1.41 KiB)


4-element Vector{Int64}:
  4
  7
  9
 10

In [7]:
xx = rand(1000)
ww = abs.(rand(1000))
qq = [0.0, 0.1, 0.15, 0.25, 0.6, 0.65, 0.75, 0.9, 0.95, 1.0]
qq = [0.0, 0.15, 0.25, 0.1, 0.65, 0.6, 0.9, 0.75, 0.95, 1.0]
println("Min xx = $(minimum(xx))")
println("Max xx = $(maximum(xx))")
@btime wquantile(xx, ww, qq; chk=true) 

Min xx = 0.00018231354889852724
Max xx = 0.9999867733983173
  24.062 μs (12 allocations: 36.67 KiB)


10-element Vector{Float64}:
 0.00018231354889852724
 0.08304788516602968
 0.12282526581567232
 0.2117282341724166
 0.5662221462807308
 0.6189234888999643
 0.7199337301998084
 0.8857760399091509
 0.94027531623847
 0.9999867733983173

In [8]:
XX = rand(10000, 500)
ww = abs.(rand(10000))
qq = [0.0, 0.1, 0.15, 0.25, 0.6, 0.65, 0.75, 0.9, 0.95, 1.0]

10-element Vector{Float64}:
 0.0
 0.1
 0.15
 0.25
 0.6
 0.65
 0.75
 0.9
 0.95
 1.0

In [9]:
println("Min xx = $(minimum(XX))")
println("Max xx = $(maximum(XX))")

Min xx = 5.567887206847644e-8
Max xx = 0.999999605906421


In [12]:
@btime wquantile(XX, ww, qq)

  39.710 ms (8784 allocations: 191.16 MiB)


10×500 Matrix{Float64}:
 0.000125912  3.96732e-5  0.000251792  …  1.12335e-5  2.40704e-5  0.000272487
 0.101438     0.102493    0.095962        0.100461    0.0965333   0.099563
 0.150045     0.150532    0.149234        0.151619    0.150704    0.150275
 0.247114     0.255014    0.25123         0.254841    0.246956    0.250277
 0.597569     0.599782    0.606599        0.607671    0.602605    0.603272
 0.648916     0.649637    0.653914     …  0.659318    0.652976    0.650109
 0.751883     0.744484    0.753978        0.754846    0.748435    0.753746
 0.902718     0.896205    0.900363        0.899899    0.896164    0.898482
 0.949315     0.94778     0.949298        0.951811    0.948976    0.948872
 0.999946     0.999875    0.999988        0.999864    0.99991     0.999892

In [14]:
size(XX)

(10000, 500)

In [23]:
W = reshape(repeat(ww, 500), (10000, 500))

10000×500 Matrix{Float64}:
 7.06754e-5   7.06754e-5   7.06754e-5   …  7.06754e-5   7.06754e-5
 8.40257e-5   8.40257e-5   8.40257e-5      8.40257e-5   8.40257e-5
 0.000100783  0.000100783  0.000100783     0.000100783  0.000100783
 8.05404e-5   8.05404e-5   8.05404e-5      8.05404e-5   8.05404e-5
 0.000110108  0.000110108  0.000110108     0.000110108  0.000110108
 0.000161535  0.000161535  0.000161535  …  0.000161535  0.000161535
 6.70603e-5   6.70603e-5   6.70603e-5      6.70603e-5   6.70603e-5
 0.000151695  0.000151695  0.000151695     0.000151695  0.000151695
 1.0416e-5    1.0416e-5    1.0416e-5       1.0416e-5    1.0416e-5
 0.000126103  0.000126103  0.000126103     0.000126103  0.000126103
 0.000117724  0.000117724  0.000117724  …  0.000117724  0.000117724
 7.61533e-5   7.61533e-5   7.61533e-5      7.61533e-5   7.61533e-5
 0.000113345  0.000113345  0.000113345     0.000113345  0.000113345
 ⋮                                      ⋱               
 8.81319e-5   8.81319e-5   8.81319e-5  

In [24]:
@btime wquantile(XX, W, qq)

  268.577 ms (1029 allocations: 191.46 MiB)


10×500 Matrix{Float64}:
 0.000125912  3.96732e-5  0.000251792  …  1.12335e-5  2.40704e-5  0.000272487
 0.101438     0.102493    0.095962        0.100461    0.0965333   0.099563
 0.150045     0.150532    0.149234        0.151619    0.150704    0.150275
 0.247114     0.255014    0.25123         0.254841    0.246956    0.250277
 0.597569     0.599782    0.606599        0.607671    0.602605    0.603272
 0.648916     0.649637    0.653914     …  0.659318    0.652976    0.650109
 0.751883     0.744484    0.753978        0.754846    0.748435    0.753746
 0.902718     0.896205    0.900363        0.899899    0.896164    0.898482
 0.949315     0.94778     0.949298        0.951811    0.948976    0.948872
 0.999946     0.999875    0.999988        0.999864    0.99991     0.999892